### ISSUE TITLE
Getting an error with the code

### ISSUE THREAD

**Issue by kevinkt** [ofat/yashop-ses#11]
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found

Does anyone know why this error is happening?

**Comment by ofat** [comment]
Because you're trying to load xml from not valid xml string

**Comment by kevinkt** [comment]
Sorry but what does that mean? I'm just using the following code. Where is
the XML not loading?

Yii::$app->mailer->compose()
    ->setFrom('confirmation@vyper.io')
->setReplyTo($contest_creator_email)
    ->setTo($email)
    ->setSubject('Contest confirmation + Bonus Inside')
    ->setTextBody('Plain text content')
    ->setHtmlBody('<b>HTML content</b>')
    ->send();



On Wed, Jan 13, 2016 at 6:58 AM, Vitaliy Ofat <notifications@github.com>
wrote:

> Because you're trying to load xml from not valid xml string
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ofat/yashop-ses/issues/11#issuecomment-171320766>.
>



-- 
--
Kevin Tang

**Comment by husstahn** [comment]
You need to add (string) like this
$this->response->body = simplexml_load_string(**(string)**$this->response->body)

**Comment by kevinkt** [comment]
The error code is the same even after adding it.
