### ISSUE TITLE
Error when trying to send email

### ISSUE THREAD

**Issue by alexweb** [ofat/yashop-ses#7]
When I'm trying to send email I get this error:

PHP Warning 'yii\base\ErrorException' with message 'simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found' 
in /var/www/html/mysite/vendor/ofat/yii2-yashop-ses/libs/SimpleEmailServiceRequest.php:147

Do you know how to fix this?

**Comment by alexweb** [comment]
Below is response from SES
```php
<pre>stdClass Object
(
    [error] => 
    [body] => 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-993086003 ta4CIzijQDS6fNIWQObW
500 Error: command not implemented
500 Error: command not implemented
500 Error: command not implemented
500 Error: command not implemented
500 Error: command not implemented
500 Error: command not implemented
500 Error: command not implemented
500 Error: command not implemented
500 Error: command not implemented
500 Error: bad syntax
501 Input line length is too long!

    [code] => 0
)
```

**Comment by ofat** [comment]
Can you show your code and config that you use for sending?

**Comment by alexweb** [comment]
Sure. 
My config:
'mail' => [
            'class' => 'yashop\ses\Mailer',
            'viewPath' => '@app/mail',
            /*
             * AmazonSES credentials
             */
            'access_key' => '<my_key_here>',
            'secret_key' => '<my_secret_here>',
            'host' => 'email-smtp.us-east-1.amazonaws.com',
        ],```php

```

Code for sending:
```php
                    Yii::$app->mail->compose('sign_up', ['user' => $user])
                        ->setFrom(Yii::$app->params['adminEmail'])
                        ->setTo($this->email)
                        ->setSubject('Welcome to ' . Yii::$app->name)
                        ->send();
```

**Comment by ofat** [comment]
Change host to 'email.us-east-1.amazonaws.com'
You are trying to send email though smtp host

**Comment by alexweb** [comment]
Works! Thanks)

**Comment by nagashayan** [comment]
Undefined property: yashop\ses\libs\SimpleEmailServiceRequest::$resource

my config
'mail' => [
        'viewPath' => '@common/mail',
        'class' => 'yashop\ses\Mailer',
        'access_key' => '*****',
        'secret_key' => '****',
        //'host' => 'email.us-east-1.amazonaws.com',
        ],

**Comment by iblessedi** [comment]
Why this issue is being closed? It is not resolved!

**Comment by iblessedi** [comment]
Yii::$app->mailer->getSES()->enableVerifyPeer(false); - this code fixed this issue for me

**Comment by VahanMuradyan** [comment]
Good day. 
Can you please help me to solve a problem connected with mail sending. 
The error is the following 
"PHP Warning 'yii\base\ErrorException' with message 'simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found'
"

I have used "prasanth-gandiva/yii2-yashop-ses"  class
The configs are set like http://prntscr.com/f0j66i
Here is the code for sending email http://prntscr.com/f0j6f4
Here is the result http://prntscr.com/f0j6uc   ,  http://prntscr.com/f0jcnu

Thank you in advance. 
Best regards

**Comment by nagashayan** [comment]
which file is SimpleEmailServiceRequest.php?
