### ISSUE TITLE
This enables the usage of free tier?

### ISSUE THREAD

**Issue by tehmaestro** [ofat/yashop-ses#8]
Hi. I was wondering if this is using the free usage tier of 62,000 monthly emails, as specified here https://aws.amazon.com/ses/pricing/ ?

**Comment by ofat** [comment]
Yes, it's uses free tier

**Comment by tehmaestro** [comment]
Cool, thank you, sorry for opening this up.

**Comment by tehmaestro** [comment]
I just tried it, and it works, it it awesome, however I get errors saying 'Address not verified' . I guess I need to raise my "sandbox" environment from SES panel in AWS console right?
